# Generated by Django 4.2.4 on 2023-12-16 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicleMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_camp', models.DateField(auto_now_add=True)),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaQOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_7_dies', models.BooleanField()),
                ('mes_3_dies_abunda', models.BooleanField()),
                ('regla_molesta', models.BooleanField()),
                ('mancha_ropa', models.BooleanField()),
                ('manchar_asiento', models.BooleanField()),
                ('evitar_activitats', models.BooleanField()),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('compresa_poc_tacada', models.IntegerField()),
                ('compresa_mitja_tacada', models.IntegerField()),
                ('compresa_molt_tacada', models.IntegerField()),
                ('compresa_coaguls', models.IntegerField()),
                ('tampo_poc_tacat', models.IntegerField()),
                ('tampo_mitja_tacat', models.IntegerField()),
                ('tampo_molt_tacat', models.IntegerField()),
                ('tampo_coaguls', models.IntegerField()),
                ('cicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ciclemenstrual')),
            ],
        ),
    ]
