# Generated by Django 4.2.4 on 2023-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermodel_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='token',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
