# Generated by Django 4.2.4 on 2023-12-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usermodel_token_usermodel_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclemenstrual',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel'),
        ),
        migrations.AlterField(
            model_name='encuestaqol',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodel'),
        ),
    ]
