# Generated by Django 4.2.4 on 2023-12-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ciclemenstrual_usuari_alter_encuestaqol_usuari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaqol',
            name='evitar_activitats',
        ),
        migrations.RemoveField(
            model_name='encuestaqol',
            name='mancha_ropa',
        ),
        migrations.RemoveField(
            model_name='encuestaqol',
            name='manchar_asiento',
        ),
        migrations.RemoveField(
            model_name='encuestaqol',
            name='mes_3_dies_abunda',
        ),
        migrations.RemoveField(
            model_name='encuestaqol',
            name='mes_7_dies',
        ),
        migrations.RemoveField(
            model_name='encuestaqol',
            name='regla_molesta',
        ),
        migrations.AddField(
            model_name='encuestaqol',
            name='punts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
