# Generated by Django 4.2.4 on 2023-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_encuestaqol_evitar_activitats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamenstrual',
            name='compresa_coaguls',
        ),
        migrations.RemoveField(
            model_name='diamenstrual',
            name='compresa_mitja_tacada',
        ),
        migrations.RemoveField(
            model_name='diamenstrual',
            name='compresa_molt_tacada',
        ),
        migrations.RemoveField(
            model_name='diamenstrual',
            name='compresa_poc_tacada',
        ),
        migrations.RemoveField(
            model_name='diamenstrual',
            name='tampo_coaguls',
        ),
        migrations.RemoveField(
            model_name='diamenstrual',
            name='tampo_mitja_tacat',
        ),
        migrations.RemoveField(
            model_name='diamenstrual',
            name='tampo_molt_tacat',
        ),
        migrations.RemoveField(
            model_name='diamenstrual',
            name='tampo_poc_tacat',
        ),
        migrations.AddField(
            model_name='diamenstrual',
            name='punts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
